const URL = "http://localhost:5000";
export const txtShowMethods = {
  simpleUrl: `${URL}/v1/web/login/smplie`,
  simpleText: "در خواست 'post' ساده برای ثبت نام",
  simpleMethod: "post",
  proUrl: `${URL}/v1/web/login/pro`,
  proText: "در خواست 'post' ثبت نام . گرفتن توکن و ذخیره توکن ",
  proMethod: "post",
  get: "get",
  listUrlParams: `${URL}/v1/web/list`,
  listUrlId: `${URL}/v1/web/list/:page`,
  listHttpId: `${URL}/v1/web/list/1`,
  listTextParams: "در خواست 'get' گرفتن یک لیست همراه با صفحه بندی",
  listNew: "در خواست 'post' برای ایجاد یک آیتم جدید",
  listUrl: `${URL}/v1/web/list`,
  listUpdate: "در خواست 'post' برای ویرایش آیتم",
  listUpdatePut: "در خواست 'put' برای ویرایش آیتم",
  put: "put",
  delete: "delete",
  listDeleteUrl: `${URL}/v1/web/list`,
  listDelete: "در خواست 'delete' برای حذف آیتم",
  listDeleteUrlId: `${URL}/v1/web/list/:id`,
  listHttpDeleteId: `${URL}/v1/web/list/1`,
  token: ` برای در خواست های زیر نیاز به توکن هست. برای گرفتن توکن با ${URL}/v1/web/login/pro ثبت نام کرده و توکن خود را ذخیره کنید.`,
  getUserP: `${URL}/v1/web/list/user`,
  getUserU: `${URL}/v1/web/list/user/:id`,
  userHttpId: `${URL}/v1/web/list/user/1`,
  userText: "در خواست 'get' گرفتن اطلاعات کاربر",
};
